module StructHelpers

export @batteries
export @battery
export @enumbatteries
export @enumbattery

import ConstructionBase: getproperties, constructorof, setproperties

include("showrepr.jl")

# `$SH.foo` in macro emissions interpolates the StructHelpers module value
# directly into the generated AST. This resolves via `getproperty` at the
# call site without requiring `import StructHelpers` (or any caller-side
# binding) — callers only need a package that re-exports through to here.
# `ST` is still a stable Symbol because the StructTypes module isn't
# loaded eagerly; the `string_conversion` branch of `@enumbatteries` emits
# `import StructTypes as $ST` and the caller must have StructTypes itself.
const SH = @__MODULE__
const ST = Symbol("#StructTypes0xcf319831da055023") # a gensym causes Revise.jl issues

"""
    hash_eq_as(obj)

This allows to fine tune the behavior or `hash`, `==` and `isequal` for structs decorated by [`@batteries`](@ref).
For instances the generated `isequal` method looks like this:
```julia
function Base.isequal(o1::T, o2::T)
    proxy1 = StructHelpers.hash_eq_as(o1)
    proxy2 = StructHelpers.hash_eq_as(o2)
    isequal(proxy1, proxy2)
end
```
Overloading `hash_eq_as` is useful for instance if you want to skip certain fields
of `obj` or handle them in a special way.
"""
function hash_eq_as(obj)
    # it would be better to just use getproperties
    # but this would cause hashed to change, which we want to
    # keep backwards compatible for now.
    #
    # TODO: Change to getproperties once we want to make a hash breaking change
    Tuple(getproperties(obj))
end

"""
    has_batteries(T::Type)::Bool

Check if `@batteries` or `@enumbatteries` was applied to `T`.
"""
function has_batteries(::Type)::Bool
    false
end

"""
    default_keywords(::Type)::NamedTuple

Return a `NamedTuple` of default values for the fields of a struct.
Overload this for your type to supply defaults that are picked up by
the keyword constructor and the keyword `show` generated by
[`@batteries`](@ref) (with `kwconstructor=true` / `kwshow=true`).

* The keyword constructor uses the values returned here as defaults
  for the corresponding keyword arguments. Fields not present in the
  returned `NamedTuple` remain required.
* `kwshow` skips fields whose value is `isequal` to the default
  returned here.

# Example
```julia
struct Point
    x::Float64
    y::Float64
end
@batteries Point kwconstructor=true kwshow=true
StructHelpers.default_keywords(::Type{Point}) = (x = 0.0, y = 0.0)

Point()                       # Point(0.0, 0.0)
Point(x = 1.0)                # Point(1.0, 0.0)
sprint(show, Point(1.0, 0.0)) # "Point(x = 1.0)"
```
"""
function default_keywords(::Type)
    NamedTuple()
end

"""
    kwconstruct(::Type{T}; field1, field2, ...) -> T

Strict keyword constructor: every field of `T` is a required keyword argument.
A method for each type decorated with `@batteries T kwconstructor=true` is
generated by the macro. The user-facing `T(; kwargs...)` constructor merges
[`default_keywords`](@ref) with the supplied kwargs and forwards to this
helper.
"""
function kwconstruct end

@inline function structural_eq(o1, o2)
    getproperties(o1) == getproperties(o2)
end
@inline function structural_isequal(o1, o2)
    isequal(getproperties(o1), getproperties(o2))
end

function start_hash(o, h, typesalt::Nothing)
    Base.hash(typeof(o), h)
end
function start_hash(o, h, typesalt)
    Base.hash(typesalt, h)
end

@inline function structural_hash(o, h::UInt, typesalt=nothing)::UInt
    h = start_hash(o, h, typesalt)
    nt = Tuple(getproperties(o))
    Base.hash(nt, h)
end
"""
    kwshow(io::IO, o)

Show `o` as `T(f1 = v1, f2 = v2, ...)`, listing every field as a keyword
argument. The output is recreatable via the keyword constructor (see
[`@batteries`](@ref) with `kwconstructor=true`).

For a representation that picks the shortest constructor call and omits
default values, see [`showrepr`](@ref).
"""
function kwshow(io::IO, o)
    print(io, typeof(o))
    print(io, "(")
    defaults = default_keywords(typeof(o))
    nt = getproperties(o)
    first = true
    for (k, v) in pairs(nt)
        if haskey(defaults, k) && isequal(v, defaults[k])
            continue
        end
        if first
            first = false
        else
            print(io, ", ")
        end
        print(io, k, " = ")
        show(io, v)
    end
    print(io, ")")
end

function def_getproperties(T, propertynames)
    body = Expr(:tuple)
    for pname in propertynames
        ex = :($pname = o.$pname)
        push!(body.args, ex)
    end
    :($SH.getproperties(o::$T) = $body)
end

function def_selfconstructor(T)
    :($T(self::$T) = self)
end

function def_kwconstructor(T, propertynames)
    # Strict, fully-required keyword constructor on `kwconstruct(::Type{T}; ...)`.
    # Julia raises its own UndefKeywordError / unsupported-kwarg errors for us.
    strict_sig = Expr(:call,
        :($SH.kwconstruct),
        Expr(:parameters, propertynames...),
        :(::$Type{<:$T}),
    )
    strict_def = :($strict_sig = $T($(propertynames...)))

    # User-facing T(; kwargs...) merges default_keywords once with the
    # supplied kwargs and forwards. Later splats win, so user kwargs override
    # defaults.
    user_sig = Expr(:call, T, Expr(:parameters, Expr(:..., :kwargs)))
    user_body = :($SH.kwconstruct($T; $SH.default_keywords($T)..., kwargs...))
    user_def = Expr(:function, user_sig, user_body)

    Expr(:block, strict_def, user_def)
end

const BATTERIES_DEFAULTS = (
    eq            = true,
    isequal       = true,
    hash          = true ,
    kwconstructor = false,
    selfconstructor = true,
    kwshow        = false,
    showrepr      = false,
    getproperties = true ,
    constructorof = true ,
    typesalt      = nothing,
    StructTypes   = false,
)

const BATTERIES_DOCSTRINGS = (
    eq            = "Define `Base.(==)` structurally.",
    isequal       = "Define `Base.isequal` structurally.",
    hash          = "Define `Base.hash` structurally.",
    kwconstructor = "Add a keyword constructor. Defaults can be supplied by overloading [`default_keywords`](@ref).",
    selfconstructor = "Add a constructor of the for `T(self::T) = self`",
    kwshow        = "Overload `Base.show` such that the names of each field are printed. Fields whose value is `isequal` to the value returned by [`default_keywords`](@ref) are omitted.",
    showrepr      = "Overload `Base.show` to print a heuristically short constructor call that recreates the object, omitting default values. Mutually exclusive with `kwshow`.",
    getproperties = "Overload `ConstructionBase.getproperties`.",
    constructorof = "Overload `ConstructionBase.constructorof`.",
    typesalt      = "Only used if `hash=true`. In this case the `hash` will be purely computed from `typesalt` and `hash_eq_as(obj)`. The type `T` will not be used otherwise. This makes the hash more likely to stay constant, when executing on a different machine or julia version",
    StructTypes   = "Overload `StructTypes.StructType` to be `Struct()`. Needs the `StructTypes.jl` package to be installed.",
)

if (keys(BATTERIES_DEFAULTS) != keys(BATTERIES_DOCSTRINGS))
    error("""
          keys(BATTERIES_DEFAULTS) == key(BATTERIES_DOCSTRINGS) must hold.
          Got:
          keys(BATTERIES_DEFAULTS) = $(keys(BATTERIES_DEFAULTS))
          keys(BATTERIES_DOCSTRINGS) = $(keys(BATTERIES_DOCSTRINGS))
    """)
end
@assert keys(BATTERIES_DEFAULTS) == keys(BATTERIES_DOCSTRINGS)

function doc_batteries_options()
    lines = map(propertynames(BATTERIES_DEFAULTS)) do key
        "* **$key** = $(BATTERIES_DEFAULTS[key]):\n $(BATTERIES_DOCSTRINGS[key])"
    end
    join(lines, "\n")
end

const BATTERIES_ALLOWED_KW = keys(BATTERIES_DEFAULTS)

# Same shape as `BATTERIES_DEFAULTS`, but with every Bool flipped to `false`
# and `typesalt` left at `nothing`. Used as the base nametuple for the
# `@battery` macro, where the user opts in to each desired battery
# explicitly. Derived programmatically so it stays in sync if
# `BATTERIES_DEFAULTS` ever gains a new option.
const BATTERIES_NONE = (;
    (k => (v isa Bool ? false : v) for (k, v) in pairs(BATTERIES_DEFAULTS))...
)
@assert keys(BATTERIES_NONE) == keys(BATTERIES_DEFAULTS)

"""

    @batteries T [options]

Automatically derive several methods for type `T`.

# Example
```julia
struct S
    a
    b
end

@batteries S
@batteries S hash=false         # don't overload `Base.hash`
@batteries S kwconstructor=true # add a keyword constructor
@batteries S kwconstructor      # bare symbol is shorthand for `kwconstructor=true`
```

# Reusing options across many structs

Each `option` argument can also be an expression that evaluates to a
`NamedTuple`; its fields are spliced into the keyword list. This lets
you share a configuration across many types:

```julia
const config = (kwshow=true, kwconstructor=true, eq=false)

@batteries S1 config
@batteries S2 config typesalt=0xdeadbeef   # override `typesalt` only
@batteries S3 (kwshow=true, eq=false)      # inline NamedTuple literal
```

Later arguments override earlier ones (last-write-wins), so explicit
overrides after a config splat behave as expected. The bare-flag
shorthand is reserved for call sites and not stored in `NamedTuple`s
— spell config entries as `flag = true`.

## Bare-symbol resolution

A bare symbol argument is resolved by checking the calling module
*first*: if it names a `NamedTuple` binding, that binding is splatted;
otherwise, if it names a flag, it is treated as `flag = true`. User
bindings winning over flag names is deliberate, so adding new flags
in future versions of `StructHelpers` cannot silently shadow a user's
config binding that happens to share the new flag's name. To adopt a
newly added flag with a colliding binding name, either rename the
binding or spell the flag explicitly as `flag = true`.

Supported options and defaults are:

$(doc_batteries_options())

See also [`@battery`](@ref) for an opt-in variant that derives only the
listed batteries instead of starting from the defaults, and
[`hash_eq_as`](@ref).
"""
macro batteries(T, kw...)
    def_batteries(__module__, T, kw, BATTERIES_DEFAULTS) |> esc
end

"""

    @battery T [options]

Like [`@batteries`](@ref) but with every default flipped to `false`: only
the batteries the user lists explicitly are derived. The bare-flag
shorthand makes call sites read as a checklist of behaviors to install.

# Example
```julia
struct S
    a
    b
end

@battery S kwconstructor       # only define the keyword constructor
@battery S eq isequal hash     # only structural ==, isequal, hash
@battery S hash typesalt=0xab  # only define hash, with stable typesalt
```

`@battery` accepts the same `NamedTuple` config splatting as
[`@batteries`](@ref):

```julia
const minimal = (kwshow=true, kwconstructor=true)
@battery T minimal             # only the two batteries in `minimal`
@battery T minimal eq=true     # the two from `minimal` plus structural ==
```

Supported options are the same as for [`@batteries`](@ref); only the
defaults differ (every Bool defaults to `false`, `typesalt` to `nothing`).
"""
macro battery(T, kw...)
    def_batteries(__module__, T, kw, BATTERIES_NONE) |> esc
end

# Shared codegen for `@batteries` / `@battery`. The two macros differ only
# in `base`: `BATTERIES_DEFAULTS` (most batteries on) vs `BATTERIES_NONE`
# (everything off). The same validation and emission logic is used in both
# cases.
function def_batteries(__module__, T, kw, base)
    nt = parse_all_macro_kw(kw, __module__, propertynames(BATTERIES_DEFAULTS))
    for (pname, val) in pairs(nt)
        if !(pname in propertynames(BATTERIES_DEFAULTS))
            error("""
                Unsupported keyword.
                Offending Keyword: $pname
                allowed: $BATTERIES_ALLOWED_KW
                Got: $nt
            """)
        end
        if pname == :typesalt
            check_typesalt(val)
        elseif val isa Bool
            # pass
        else
            error("""
                Bad keyword argument value:
                Got: $nt
                Offending Keyword: $pname
                Offending value  : $(repr(val))
            """)
        end
    end
    nt = merge(base, nt)
    ret = quote end

    need_fieldnames = nt.kwconstructor || nt.getproperties
    fieldnames = need_fieldnames ? Base.fieldnames(Base.eval(__module__, T)) : ()
    need_StructTypes = nt.StructTypes
    if need_StructTypes
        push!(ret.args, :(import StructTypes as $ST))
    end
    if nt.hash
        def = :(function $(Base).hash(o::$T, h::$UInt)
            h = ($start_hash)(o, h, $(nt.typesalt))
            proxy = ($hash_eq_as)(o)
            $(Base).hash(proxy, h)
        end
        )
        push!(ret.args, def)
    end
    if nt.eq
        def = :(function $(Base).:(==)(o1::$T, o2::$T)
            ($hash_eq_as)(o1) == ($hash_eq_as)(o2)
        end
        )
        push!(ret.args, def)
    end
    if nt.isequal
        def = :(function $(Base).isequal(o1::$T, o2::$T)
            $(Base).isequal($hash_eq_as(o1), $hash_eq_as(o2))
        end
        )
        push!(ret.args, def)
    end
    if nt.kwshow && nt.showrepr
        error("`kwshow` and `showrepr` are mutually exclusive; please pick at most one.")
    end
    if nt.kwshow
        def = :($(Base).show(io::$IO, o::$T) = $(kwshow)(io, o))
        push!(ret.args, def)
    end
    if nt.showrepr
        def = :(Base.show(io::IO, o::$T) = $(showrepr)(io, o))
        push!(ret.args, def)
    end
    if nt.getproperties
        def = def_getproperties(T, fieldnames)
        push!(ret.args, def)
    end
    if nt.constructorof
        def = :($SH.constructorof(::$Type{<:$T}) = $T)
        push!(ret.args, def)
    end
    if nt.kwconstructor
        def = def_kwconstructor(T, fieldnames)
        push!(ret.args, def)
    end
    if nt.selfconstructor
        def = def_selfconstructor(T)
        push!(ret.args, def)
    end
    if nt.StructTypes
        def = :($ST.StructType(::$Type{<:$T}) = $ST.Struct())
        push!(ret.args, def)
    end
    push!(ret.args, def_has_batteries(T))
    return ret
end

# `$Type` (and friends below) interpolate the actual Core.Type value
# at quote-build time so it ends up as a literal in the resulting AST.
# That immunizes the macro against a user module that has redefined
# `Type`, `Any`, `Bool`, `UInt`, `String`, `Symbol`, or
# `AbstractString` to something else (which is exactly what happens
# when a user struct is itself named `Type` or `Any`).
function def_has_batteries(T)
    :(
        function $(SH).has_batteries(::$Type{<:$T})::$Bool
            true
        end
    )
end

function check_typesalt(typesalt)
    if !(typesalt isa Union{Nothing,Integer})
        error(
            """
            `typesalt` must be literally `nothing` or an unsigned integer. Got:
            typesalt = $(repr(typesalt))::$(typeof(typesalt))
            """
        )
    end
end

function error_parse_macro_kw(kw; comment=nothing)
    msg = """
    Expected a keyword argument of the form name = value.
    Got $(kw) instead.
    """
    if comment !== nothing
        msg = msg*comment
    end
    error(msg)
end

# Evaluate `expr` in `__module__` and return its `pairs(...)` as a
# `Vector{Pair{Symbol,Any}}`. Used to splat a config-style binding or
# an inline `(a=1, b=2)` literal into the macro's keyword stream. Errors
# with a clear message if evaluation fails or the result isn't a
# `NamedTuple`.
function eval_namedtuple_arg(expr, __module__)
    bad(reason) = error("""
        Bad argument: $(repr(expr))
        Expected a flag, `name = value`, or an expression evaluating to a `NamedTuple`.
        $reason
    """)
    val = try
        Base.eval(__module__, expr)
    catch e
        bad("Evaluation failed:\n$(sprint(showerror, e))")
    end
    val isa NamedTuple || bad("Got: $(repr(val))::$(typeof(val))")
    return Pair{Symbol,Any}[k => v for (k, v) in pairs(val)]
end

function parse_single_macro_kw(kw, __module__, allowed_keys)
    # Bare-symbol shorthand: `flag` is sugar for `flag=true`. Lets users
    # write `@batteries T kwconstructor` instead of
    # `@batteries T kwconstructor=true`. We resolve a bare symbol by
    # checking the caller's module *first*: if it names a `NamedTuple`
    # binding, we splat it as config; otherwise, if it names a flag, we
    # treat it as `flag=true`. User bindings winning over flag names is
    # deliberate — it means StructHelpers can add new flags in future
    # versions without silently shadowing a user's config binding that
    # happens to share the new flag's name. The user only needs to
    # rename their binding (or spell the new flag as `flag=true`) to
    # adopt the new option.
    if kw isa Symbol
        if isdefined(__module__, kw)
            val = Base.eval(__module__, kw)
            if val isa NamedTuple
                return Pair{Symbol,Any}[k => v for (k, v) in pairs(val)]
            end
        end
        if kw in allowed_keys
            return Pair{Symbol,Any}[kw => true]
        end
        error("""
            Bad argument: $(repr(kw))
            A bare symbol must either name a flag or a `NamedTuple` binding
            in the calling module. Got neither.
            Allowed flags: $(collect(allowed_keys))
        """)
    end
    if Meta.isexpr(kw, Symbol("="))
        length(kw.args) == 2 || error_parse_macro_kw(kw)
        key, val = kw.args
        key isa Symbol || error_parse_macro_kw(kw, comment="key = $key must be a symbol")
        return Pair{Symbol,Any}[key => val]
    end
    # Anything else: try to evaluate as a NamedTuple-valued expression.
    # This supports inline literals like `(kwshow=true, eq=false)` and
    # arbitrary expressions that resolve to a NamedTuple.
    return eval_namedtuple_arg(kw, __module__)
end

# Fold all macro arguments into a single NamedTuple. Later arguments
# override earlier ones (last-write-wins, courtesy of NamedTuple
# construction), so the common pattern `@batteries S config typesalt=0xab`
# cleanly extends a config with explicit overrides.
parse_all_macro_kw(kw, __module__, allowed_keys) =
    (; (p for k in kw for p in parse_single_macro_kw(k, __module__, allowed_keys))...)

################################################################################
#### enum
################################################################################
function ifelsechain(
        cond_code_pairs,
        rest
    )
    if length(cond_code_pairs) == 0
        return rest
    elseif length(cond_code_pairs) == 1
        cond, code = only(cond_code_pairs)
        Expr(:if, cond, code, rest)
    else
        cond, code = cond_code_pairs[end]
        ifelsechain(
            cond_code_pairs[begin:end-1],
            Expr(:elseif, cond, code, rest),
        )
    end
end

function enum_from_string end
function enum_from_symbol end
function string_from_enum(x)::String
    string_from_enum_generic(x)
end
function string_from_enum_generic(x)::String
    string(x)
end

function symbol_from_enum(x)::Symbol
    symbol_from_enum_generic(x)
end
function symbol_from_enum_generic(x)::Symbol
    Symbol(string_from_enum_generic(x))
end

function def_enum_from_string(T)::Expr
    body = def_enum_from_string_or_symbol_body(string_from_enum, T)
    :(
      function $SH.enum_from_string(::$Type{$T}, s::$String)::$T
          $body
      end
     )
end
function def_enum_from_symbol(T)::Expr
    body = def_enum_from_string_or_symbol_body(QuoteNode∘symbol_from_enum, T)
    :(
      function $SH.enum_from_symbol(::$Type{$T}, s::$Symbol)::$T
          $body
      end
     )
end

@noinline function throw_no_matching_instance(f,T,s)
    msg = """
    Cannot instaniate enum `T` from `s`. Got:
    s = $(repr(s))
    T = $(T)
    allowed values for s = $(map(f, instances(T)))
    """
    throw(ArgumentError(msg))
end

function def_symbol_or_string_from_enum_body(s_from_enum_generic, T)::Expr
    default = :($s_from_enum_generic(obj))
    matcharms = [
        :(obj === $inst) => QuoteNode(s_from_enum_generic(inst)) for inst in instances(T)
                ]
    ifelsechain(matcharms, default)
end

function def_symbol_from_enum(T)::Expr
    body = def_symbol_or_string_from_enum_body(symbol_from_enum_generic, T)
    :(
      function $SH.symbol_from_enum(obj::$T)::$Symbol
          $body
      end
     )
end

function def_string_from_enum(T)::Expr
    body = def_symbol_or_string_from_enum_body(string_from_enum_generic, T)
    :(
      function $SH.string_from_enum(obj::$T)::$String
          $body
      end
     )
end

function def_enum_from_string_or_symbol_body(f,T)
    err = :($throw_no_matching_instance($f,$T,s))
    matcharms = [
        :(s === $(f(inst))) => inst for inst in instances(T)
    ]
    ifelsechain(matcharms, err)
end

const ENUM_BATTERIES_DEFAULTS = (
    string_conversion = false,
    symbol_conversion = false,
    selfconstructor   = BATTERIES_DEFAULTS.selfconstructor,
    hash              = false,
    typesalt          = BATTERIES_DEFAULTS.typesalt,
)

const ENUM_BATTERIES_DOCSTRINGS = (
    string_conversion = "Add `convert(MyEnum, ::String)`, `MyEnum(::String)`, `convert(String, ::MyEnum)` and `String(::MyEnum)`",
    symbol_conversion = "Add `convert(MyEnum, ::Symbol)`, `MyEnum(::Symbol)`, `convert(Symbol, ::MyEnum)` and `Symbol(::MyEnum)`",
    selfconstructor   = BATTERIES_DOCSTRINGS.selfconstructor,
    hash              = BATTERIES_DOCSTRINGS.hash,
    typesalt          = BATTERIES_DOCSTRINGS.typesalt,
)

if (keys(ENUM_BATTERIES_DEFAULTS) != keys(ENUM_BATTERIES_DOCSTRINGS))
    error("""
          keys(ENUM_BATTERIES_DEFAULTS) == key(ENUM_BATTERIES_DOCSTRINGS) must hold.
          Got:
          keys(ENUM_BATTERIES_DEFAULTS) = $(keys(ENUM_BATTERIES_DEFAULTS))
          keys(ENUM_BATTERIES_DOCSTRINGS) = $(keys(ENUM_BATTERIES_DOCSTRINGS))
    """)
end
@assert keys(ENUM_BATTERIES_DEFAULTS) == keys(ENUM_BATTERIES_DOCSTRINGS)

function doc_enum_batteries_options()
    lines = map(propertynames(ENUM_BATTERIES_DEFAULTS)) do key
        "* **$key** = $(ENUM_BATTERIES_DEFAULTS[key]):\n $(ENUM_BATTERIES_DOCSTRINGS[key])"
    end
    join(lines, "\n")
end

const ENUM_BATTERIES_ALLOWED_KW = keys(ENUM_BATTERIES_DEFAULTS)

# Same shape as `ENUM_BATTERIES_DEFAULTS`, but with every Bool flipped to
# `false` and `typesalt` left at `nothing`. Used as the base nametuple for
# the `@enumbattery` macro. Derived programmatically so it stays in sync
# if `ENUM_BATTERIES_DEFAULTS` ever gains a new option.
const ENUM_BATTERIES_NONE = (;
    (k => (v isa Bool ? false : v) for (k, v) in pairs(ENUM_BATTERIES_DEFAULTS))...
)
@assert keys(ENUM_BATTERIES_NONE) == keys(ENUM_BATTERIES_DEFAULTS)

"""

    @enumbatteries T [options]

Automatically derive several methods for Enum type `T`.

# Example
```julia
@enum Color Red Blue Yellow
@enumbatteries Color
@enumbatteries Color hash=false # don't overload `Base.hash`
@enumbatteries Color symbol_conversion=true # allow convert(Color, :Blue), Color(:Blue), convert(Symbol, Blue), Symbol(Blue)
@enumbatteries Color symbol_conversion      # bare symbol is shorthand for `symbol_conversion=true`
```

Like [`@batteries`](@ref), arguments may also be `NamedTuple`-valued
expressions whose fields are spliced in (config-style):

```julia
const enum_config = (string_conversion=true, symbol_conversion=true)
@enumbatteries Color enum_config
@enumbatteries Color enum_config hash=false  # override
```

Supported options and defaults are:

$(doc_enum_batteries_options())

See also [`@enumbattery`](@ref) for an opt-in variant that derives only
the listed batteries instead of starting from the defaults.
"""
macro enumbatteries(T, kw...)
    def_enumbatteries(__module__, T, kw, ENUM_BATTERIES_DEFAULTS) |> esc
end

"""

    @enumbattery T [options]

Like [`@enumbatteries`](@ref) but with every default flipped to `false`:
only the batteries the user lists explicitly are derived. The
`enum_from_string` / `enum_from_symbol` / `string_from_enum` /
`symbol_from_enum` methods are always defined (they have no opt-out in
`@enumbatteries` either).

# Example
```julia
@enum Color Red Blue Yellow
@enumbattery Color symbol_conversion          # only the symbol-conversion batteries
@enumbattery Color hash typesalt=0xab         # only stable hash
```
"""
macro enumbattery(T, kw...)
    def_enumbatteries(__module__, T, kw, ENUM_BATTERIES_NONE) |> esc
end

# Shared codegen for `@enumbatteries` / `@enumbattery`. The two macros
# differ only in `base`: `ENUM_BATTERIES_DEFAULTS` (most batteries on) vs
# `ENUM_BATTERIES_NONE` (everything off, except the always-on
# `enum_from_*` / `*_from_enum` methods).
function def_enumbatteries(__module__, T, kw, base)
    nt = parse_all_macro_kw(kw, __module__, propertynames(ENUM_BATTERIES_DEFAULTS))
    for (pname, val) in pairs(nt)
        if !(pname in propertynames(ENUM_BATTERIES_DEFAULTS))
            error("""
                Unsupported keyword.
                Offending Keyword: $pname
                allowed: $ENUM_BATTERIES_ALLOWED_KW
                Got: $nt
            """)
        end
        if pname == :typesalt
            check_typesalt(val)
        elseif val isa Bool
            # pass
        else
            error("""
                Bad keyword argument value:
                Got: $nt
                Offending Keyword: $pname
                Offending value  : $(repr(val))
            """)
        end
    end
    # `typesalt` only makes sense with `hash=true`. If the user passed
    # `typesalt` without `hash`, infer `hash=true` so the salt isn't
    # silently ignored. Explicit `hash=false typesalt=...` still wins.
    nt = merge(base, (; hash = haskey(nt, :typesalt) || base.hash), nt)
    TT = Base.eval(__module__, T)::Type
    ret = quote end

    push!(ret.args, def_enum_from_symbol(TT))
    push!(ret.args, def_enum_from_string(TT))
    push!(ret.args, def_symbol_from_enum(TT))
    push!(ret.args, def_string_from_enum(TT))
    if nt.string_conversion
        ex1 = :($(Base).convert(::$Type{$TT}, s::$AbstractString) = $SH.enum_from_string($TT, $String(s)))
        ex2 = :($T(s::$AbstractString) = $SH.enum_from_string($TT, $String(s)))
        ex3 = :($(Base).convert(::$Type{$String}, x::$T) = $SH.string_from_enum(x))
        ex4 = :($(Base).String(x::$T) = $SH.string_from_enum(x))
        push!(ret.args, ex1, ex2, ex3, ex4)
    end
    if nt.symbol_conversion
        ex1 = :($(Base).convert(::$Type{$T}, s::$Symbol) = $SH.enum_from_symbol($TT, $Symbol(s)))
        ex2 = :($T(s::$Symbol) = $SH.enum_from_symbol($TT, $Symbol(s)))
        ex3 = :($(Base).convert(::$Type{$Symbol}, x::$T) = $SH.symbol_from_enum(x))
        ex4 = :($(Base).Symbol(x::$T) = $SH.symbol_from_enum(x))
        push!(ret.args, ex1, ex2, ex3, ex4)
    end
    if nt.selfconstructor
        def = def_selfconstructor(T)
        push!(ret.args, def)
    end
    if nt.hash
        def = :(function $(Base).hash(o::$T, h::$UInt)
            h = ($start_hash)(o, h, $(nt.typesalt))
            $(Base).hash($Integer(o), h)
        end
        )
        push!(ret.args, def)
    end
    push!(ret.args, def_has_batteries(T))
    return ret
end

end #module
