module StructHelpers

export @batteries
export @enumbatteries

import ConstructionBase: getproperties, constructorof, setproperties

# `$SH.foo` in macro emissions interpolates the StructHelpers module value
# directly into the generated AST. This resolves via `getproperty` at the
# call site without requiring `import StructHelpers` (or any caller-side
# binding) — callers only need a package that re-exports through to here.
# `ST` is still a stable Symbol because the StructTypes module isn't
# loaded eagerly; the `string_conversion` branch of `@enumbatteries` emits
# `import StructTypes as $ST` and the caller must have StructTypes itself.
const SH = @__MODULE__
const ST = Symbol("#StructTypes0xcf319831da055023") # a gensym causes Revise.jl issues

"""
    hash_eq_as(obj)

This allows to fine tune the behavior or `hash`, `==` and `isequal` for structs decorated by [`@batteries`](@ref).
For instances the generated `isequal` method looks like this:
```julia
function Base.isequal(o1::T, o2::T)
    proxy1 = StructHelpers.hash_eq_as(o1)
    proxy2 = StructHelpers.hash_eq_as(o2)
    isequal(proxy1, proxy2)
end
```
Overloading `hash_eq_as` is useful for instance if you want to skip certain fields
of `obj` or handle them in a special way.
"""
function hash_eq_as(obj)
    # it would be better to just use getproperties
    # but this would cause hashed to change, which we want to
    # keep backwards compatible for now.
    #
    # TODO: Change to getproperties once we want to make a hash breaking change
    Tuple(getproperties(obj))
end

"""
    has_batteries(T::Type)::Bool

Check if `@batteries` or `@enumbatteries` was applied to `T`.
"""
function has_batteries(::Type)::Bool
    false
end

"""
    default_keywords(::Type)::NamedTuple

Return a `NamedTuple` of default values for the fields of a struct.
Overload this for your type to supply defaults that are picked up by
the keyword constructor and the keyword `show` generated by
[`@batteries`](@ref) (with `kwconstructor=true` / `kwshow=true`).

* The keyword constructor uses the values returned here as defaults
  for the corresponding keyword arguments. Fields not present in the
  returned `NamedTuple` remain required.
* `kwshow` skips fields whose value is `isequal` to the default
  returned here.

# Example
```julia
struct Point
    x::Float64
    y::Float64
end
@batteries Point kwconstructor=true kwshow=true
StructHelpers.default_keywords(::Type{Point}) = (x = 0.0, y = 0.0)

Point()                       # Point(0.0, 0.0)
Point(x = 1.0)                # Point(1.0, 0.0)
sprint(show, Point(1.0, 0.0)) # "Point(x = 1.0)"
```
"""
function default_keywords(::Type)
    NamedTuple()
end

"""
    kwconstruct(::Type{T}; field1, field2, ...) -> T

Strict keyword constructor: every field of `T` is a required keyword argument.
A method for each type decorated with `@batteries T kwconstructor=true` is
generated by the macro. The user-facing `T(; kwargs...)` constructor merges
[`default_keywords`](@ref) with the supplied kwargs and forwards to this
helper.
"""
function kwconstruct end

@inline function structural_eq(o1, o2)
    getproperties(o1) == getproperties(o2)
end
@inline function structural_isequal(o1, o2)
    isequal(getproperties(o1), getproperties(o2))
end

function start_hash(o, h, typesalt::Nothing)
    Base.hash(typeof(o), h)
end
function start_hash(o, h, typesalt)
    Base.hash(typesalt, h)
end

@inline function structural_hash(o, h::UInt, typesalt=nothing)::UInt
    h = start_hash(o, h, typesalt)
    nt = Tuple(getproperties(o))
    Base.hash(nt, h)
end
function kwshow(io::IO, o)
    print(io, typeof(o))
    print(io, "(")
    defaults = default_keywords(typeof(o))
    nt = getproperties(o)
    first = true
    for (k, v) in pairs(nt)
        if haskey(defaults, k) && isequal(v, defaults[k])
            continue
        end
        if first
            first = false
        else
            print(io, ", ")
        end
        print(io, k, " = ")
        show(io, v)
    end
    print(io, ")")
end

function def_getproperties(T, propertynames)
    body = Expr(:tuple)
    for pname in propertynames
        ex = :($pname = o.$pname)
        push!(body.args, ex)
    end
    :($SH.getproperties(o::$T) = $body)
end

function def_selfconstructor(T)
    :($T(self::$T) = self)
end

function def_kwconstructor(T, propertynames)
    # Strict, fully-required keyword constructor on `kwconstruct(::Type{T}; ...)`.
    # Julia raises its own UndefKeywordError / unsupported-kwarg errors for us.
    strict_sig = Expr(:call,
        :($SH.kwconstruct),
        Expr(:parameters, propertynames...),
        :(::$Type{<:$T}),
    )
    strict_def = :($strict_sig = $T($(propertynames...)))

    # User-facing T(; kwargs...) merges default_keywords once with the
    # supplied kwargs and forwards. Later splats win, so user kwargs override
    # defaults.
    user_sig = Expr(:call, T, Expr(:parameters, Expr(:..., :kwargs)))
    user_body = :($SH.kwconstruct($T; $SH.default_keywords($T)..., kwargs...))
    user_def = Expr(:function, user_sig, user_body)

    Expr(:block, strict_def, user_def)
end

const BATTERIES_DEFAULTS = (
    eq            = true,
    isequal       = true,
    hash          = true ,
    kwconstructor = false,
    selfconstructor = true,
    kwshow        = false,
    getproperties = true ,
    constructorof = true ,
    typesalt      = nothing,
    StructTypes   = false,
)

const BATTERIES_DOCSTRINGS = (
    eq            = "Define `Base.(==)` structurally.",
    isequal       = "Define `Base.isequal` structurally.",
    hash          = "Define `Base.hash` structurally.",
    kwconstructor = "Add a keyword constructor. Defaults can be supplied by overloading [`default_keywords`](@ref).",
    selfconstructor = "Add a constructor of the for `T(self::T) = self`",
    kwshow        = "Overload `Base.show` such that the names of each field are printed. Fields whose value is `isequal` to the value returned by [`default_keywords`](@ref) are omitted.",
    getproperties = "Overload `ConstructionBase.getproperties`.",
    constructorof = "Overload `ConstructionBase.constructorof`.",
    typesalt      = "Only used if `hash=true`. In this case the `hash` will be purely computed from `typesalt` and `hash_eq_as(obj)`. The type `T` will not be used otherwise. This makes the hash more likely to stay constant, when executing on a different machine or julia version",
    StructTypes   = "Overload `StructTypes.StructType` to be `Struct()`. Needs the `StructTypes.jl` package to be installed.",
)

if (keys(BATTERIES_DEFAULTS) != keys(BATTERIES_DOCSTRINGS))
    error("""
          keys(BATTERIES_DEFAULTS) == key(BATTERIES_DOCSTRINGS) must hold.
          Got:
          keys(BATTERIES_DEFAULTS) = $(keys(BATTERIES_DEFAULTS))
          keys(BATTERIES_DOCSTRINGS) = $(keys(BATTERIES_DOCSTRINGS))
    """)
end
@assert keys(BATTERIES_DEFAULTS) == keys(BATTERIES_DOCSTRINGS)

function doc_batteries_options()
    lines = map(propertynames(BATTERIES_DEFAULTS)) do key
        "* **$key** = $(BATTERIES_DEFAULTS[key]):\n $(BATTERIES_DOCSTRINGS[key])"
    end
    join(lines, "\n")
end

const BATTERIES_ALLOWED_KW = keys(BATTERIES_DEFAULTS)

"""

    @batteries T [options]

Automatically derive several methods for type `T`.

# Example
```julia
struct S
    a
    b
end

@batteries S
@batteries S hash=false # don't overload `Base.hash`
@batteries S kwconstructor=true # add a keyword constructor
@batteries S kwconstructor      # bare symbol is shorthand for `kwconstructor=true`
```

Supported options and defaults are:

$(doc_batteries_options())

See also [`hash_eq_as`](@ref)
"""
macro batteries(T, kw...)
    nt = parse_all_macro_kw(kw)
    for (pname, val) in pairs(nt)
        if !(pname in propertynames(BATTERIES_DEFAULTS))
            error("""
                Unsupported keyword.
                Offending Keyword: $pname
                allowed: $BATTERIES_ALLOWED_KW
                Got: $nt
            """)
        end
        if pname == :typesalt
            check_typesalt(val)
        elseif val isa Bool
            # pass
        else
            error("""
                Bad keyword argument value:
                Got: $nt
                Offending Keyword: $pname
                Offending value  : $(repr(val))
            """)
        end
    end
    nt = merge(BATTERIES_DEFAULTS, nt)
    ret = quote end

    need_fieldnames = nt.kwconstructor || nt.getproperties
    if need_fieldnames
        fieldnames = Base.fieldnames(Base.eval(__module__, T))
    end
    need_StructTypes = nt.StructTypes
    if need_StructTypes
        push!(ret.args, :(import StructTypes as $ST))
    end
    if nt.hash
        def = :(function $(Base).hash(o::$T, h::$UInt)
            h = ($start_hash)(o, h, $(nt.typesalt))
            proxy = ($hash_eq_as)(o)
            $(Base).hash(proxy, h)
        end
        )
        push!(ret.args, def)
    end
    if nt.eq
        def = :(function $(Base).:(==)(o1::$T, o2::$T)
            ($hash_eq_as)(o1) == ($hash_eq_as)(o2)
        end
        )
        push!(ret.args, def)
    end
    if nt.isequal
        def = :(function $(Base).isequal(o1::$T, o2::$T)
            $(Base).isequal($hash_eq_as(o1), $hash_eq_as(o2))
        end
        )
        push!(ret.args, def)
    end
    if nt.kwshow
        def = :($(Base).show(io::$IO, o::$T) = $(kwshow)(io, o))
        push!(ret.args, def)
    end
    if nt.getproperties
        def = def_getproperties(T, fieldnames)
        push!(ret.args, def)
    end
    if nt.constructorof
        def = :($SH.constructorof(::$Type{<:$T}) = $T)
        push!(ret.args, def)
    end
    if nt.kwconstructor
        def = def_kwconstructor(T, fieldnames)
        push!(ret.args, def)
    end
    if nt.selfconstructor
        def = def_selfconstructor(T)
        push!(ret.args, def)
    end
    if nt.StructTypes
        def = :($ST.StructType(::$Type{<:$T}) = $ST.Struct())
        push!(ret.args, def)
    end
    push!(ret.args, def_has_batteries(T))
    return esc(ret)
end

# `$Type` (and friends below) interpolate the actual Core.Type value
# at quote-build time so it ends up as a literal in the resulting AST.
# That immunizes the macro against a user module that has redefined
# `Type`, `Any`, `Bool`, `UInt`, `String`, `Symbol`, or
# `AbstractString` to something else (which is exactly what happens
# when a user struct is itself named `Type` or `Any`).
function def_has_batteries(T)
    :(
        function $(SH).has_batteries(::$Type{<:$T})::$Bool
            true
        end
    )
end

function check_typesalt(typesalt)
    if !(typesalt isa Union{Nothing,Integer})
        error(
            """
            `typesalt` must be literally `nothing` or an unsigned integer. Got:
            typesalt = $(repr(typesalt))::$(typeof(typesalt))
            """
        )
    end
end

function error_parse_macro_kw(kw; comment=nothing)
    msg = """
    Expected a keyword argument of the form name = value.
    Got $(kw) instead.
    """
    if comment !== nothing
        msg = msg*comment
    end
    error(msg)
end
function parse_single_macro_kw(kw)
    # Bare-symbol shorthand: `flag` is sugar for `flag=true`. Lets users write
    # `@batteries T kwconstructor` instead of `@batteries T kwconstructor=true`.
    # The resulting `flag => true` is then validated by the macro itself, so
    # bare symbols that don't name a Bool option (e.g. `typesalt`) still
    # produce the standard "Bad keyword argument value" error.
    kw isa Symbol && return (kw => true)
    Meta.isexpr(kw, Symbol("=")) || error_parse_macro_kw(kw)
    length(kw.args) == 2 || error_parse_macro_kw(kw)
    key, val = kw.args
    key isa Symbol || error_parse_macro_kw(kw, comment="key = $key must be a symbol")
    (key => val)
end
function parse_all_macro_kw(kw)
    pairs =  map(parse_single_macro_kw, kw)
    if !(allunique(map(first, pairs)))
        error(
            """
            Keywords must be unique. Got:
            $(kw)
            """
        )
    end
    (;pairs...)
end

################################################################################
#### enum
################################################################################
function ifelsechain(
        cond_code_pairs,
        rest
    )
    if length(cond_code_pairs) == 0
        return rest
    elseif length(cond_code_pairs) == 1
        cond, code = only(cond_code_pairs)
        Expr(:if, cond, code, rest)
    else
        cond, code = cond_code_pairs[end]
        ifelsechain(
            cond_code_pairs[begin:end-1],
            Expr(:elseif, cond, code, rest),
        )
    end
end

function enum_from_string end
function enum_from_symbol end
function string_from_enum(x)::String
    string_from_enum_generic(x)
end
function string_from_enum_generic(x)::String
    string(x)
end

function symbol_from_enum(x)::Symbol
    symbol_from_enum_generic(x)
end
function symbol_from_enum_generic(x)::Symbol
    Symbol(string_from_enum_generic(x))
end

function def_enum_from_string(T)::Expr
    body = def_enum_from_string_or_symbol_body(string_from_enum, T)
    :(
      function $SH.enum_from_string(::$Type{$T}, s::$String)::$T
          $body
      end
     )
end
function def_enum_from_symbol(T)::Expr
    body = def_enum_from_string_or_symbol_body(QuoteNode∘symbol_from_enum, T)
    :(
      function $SH.enum_from_symbol(::$Type{$T}, s::$Symbol)::$T
          $body
      end
     )
end

@noinline function throw_no_matching_instance(f,T,s)
    msg = """
    Cannot instaniate enum `T` from `s`. Got:
    s = $(repr(s))
    T = $(T)
    allowed values for s = $(map(f, instances(T)))
    """
    throw(ArgumentError(msg))
end

function def_symbol_or_string_from_enum_body(s_from_enum_generic, T)::Expr
    default = :($s_from_enum_generic(obj))
    matcharms = [
        :(obj === $inst) => QuoteNode(s_from_enum_generic(inst)) for inst in instances(T)
                ]
    ifelsechain(matcharms, default)
end

function def_symbol_from_enum(T)::Expr
    body = def_symbol_or_string_from_enum_body(symbol_from_enum_generic, T)
    :(
      function $SH.symbol_from_enum(obj::$T)::$Symbol
          $body
      end
     )
end

function def_string_from_enum(T)::Expr
    body = def_symbol_or_string_from_enum_body(string_from_enum_generic, T)
    :(
      function $SH.string_from_enum(obj::$T)::$String
          $body
      end
     )
end

function def_enum_from_string_or_symbol_body(f,T)
    err = :($throw_no_matching_instance($f,$T,s))
    matcharms = [
        :(s === $(f(inst))) => inst for inst in instances(T)
    ]
    ifelsechain(matcharms, err)
end

const ENUM_BATTERIES_DEFAULTS = (
    string_conversion = false,
    symbol_conversion = false,
    selfconstructor   = BATTERIES_DEFAULTS.selfconstructor,
    hash              = false,
    typesalt          = BATTERIES_DEFAULTS.typesalt,
)

const ENUM_BATTERIES_DOCSTRINGS = (
    string_conversion = "Add `convert(MyEnum, ::String)`, `MyEnum(::String)`, `convert(String, ::MyEnum)` and `String(::MyEnum)`",
    symbol_conversion = "Add `convert(MyEnum, ::Symbol)`, `MyEnum(::Symbol)`, `convert(Symbol, ::MyEnum)` and `Symbol(::MyEnum)`",
    selfconstructor   = BATTERIES_DOCSTRINGS.selfconstructor,
    hash              = BATTERIES_DOCSTRINGS.hash,
    typesalt          = BATTERIES_DOCSTRINGS.typesalt,
)

if (keys(ENUM_BATTERIES_DEFAULTS) != keys(ENUM_BATTERIES_DOCSTRINGS))
    error("""
          keys(ENUM_BATTERIES_DEFAULTS) == key(ENUM_BATTERIES_DOCSTRINGS) must hold.
          Got:
          keys(ENUM_BATTERIES_DEFAULTS) = $(keys(ENUM_BATTERIES_DEFAULTS))
          keys(ENUM_BATTERIES_DOCSTRINGS) = $(keys(ENUM_BATTERIES_DOCSTRINGS))
    """)
end
@assert keys(ENUM_BATTERIES_DEFAULTS) == keys(ENUM_BATTERIES_DOCSTRINGS)

function doc_enum_batteries_options()
    lines = map(propertynames(ENUM_BATTERIES_DEFAULTS)) do key
        "* **$key** = $(ENUM_BATTERIES_DEFAULTS[key]):\n $(ENUM_BATTERIES_DOCSTRINGS[key])"
    end
    join(lines, "\n")
end

const ENUM_BATTERIES_ALLOWED_KW = keys(ENUM_BATTERIES_DEFAULTS)

"""

    @enumbatteries T [options]

Automatically derive several methods for Enum type `T`.

# Example
```julia
@enum Color Red Blue Yellow
@enumbatteries Color
@enumbatteries Color hash=false # don't overload `Base.hash`
@enumbatteries Color symbol_conversion=true # allow convert(Color, :Blue), Color(:Blue), convert(Symbol, Blue), Symbol(Blue)
@enumbatteries Color symbol_conversion      # bare symbol is shorthand for `symbol_conversion=true`
```

Supported options and defaults are:

$(doc_enum_batteries_options())
"""
macro enumbatteries(T, kw...)
    nt = parse_all_macro_kw(kw)
    for (pname, val) in pairs(nt)
        if !(pname in propertynames(ENUM_BATTERIES_DEFAULTS))
            error("""
                Unsupported keyword.
                Offending Keyword: $pname
                allowed: $ENUM_BATTERIES_ALLOWED_KW
                Got: $nt
            """)
        end
        if pname == :typesalt
            check_typesalt(val)
        elseif val isa Bool
            # pass
        else
            error("""
                Bad keyword argument value:
                Got: $nt
                Offending Keyword: $pname
                Offending value  : $(repr(val))
            """)
        end
    end
    nt = merge(ENUM_BATTERIES_DEFAULTS, (; hash = haskey(nt, :typesalt)), nt)
    TT = Base.eval(__module__, T)::Type
    ret = quote end

    push!(ret.args, def_enum_from_symbol(TT))
    push!(ret.args, def_enum_from_string(TT))
    push!(ret.args, def_symbol_from_enum(TT))
    push!(ret.args, def_string_from_enum(TT))
    if nt.string_conversion
        ex1 = :($(Base).convert(::$Type{$TT}, s::$AbstractString) = $SH.enum_from_string($TT, $String(s)))
        ex2 = :($T(s::$AbstractString) = $SH.enum_from_string($TT, $String(s)))
        ex3 = :($(Base).convert(::$Type{$String}, x::$T) = $SH.string_from_enum(x))
        ex4 = :($(Base).String(x::$T) = $SH.string_from_enum(x))
        push!(ret.args, ex1, ex2, ex3, ex4)
    end
    if nt.symbol_conversion
        ex1 = :($(Base).convert(::$Type{$T}, s::$Symbol) = $SH.enum_from_symbol($TT, $Symbol(s)))
        ex2 = :($T(s::$Symbol) = $SH.enum_from_symbol($TT, $Symbol(s)))
        ex3 = :($(Base).convert(::$Type{$Symbol}, x::$T) = $SH.symbol_from_enum(x))
        ex4 = :($(Base).Symbol(x::$T) = $SH.symbol_from_enum(x))
        push!(ret.args, ex1, ex2, ex3, ex4)
    end
    if nt.selfconstructor
        def = def_selfconstructor(T)
        push!(ret.args, def)
    end
    if nt.hash
        def = :(function $(Base).hash(o::$T, h::$UInt)
            h = ($start_hash)(o, h, $(nt.typesalt))
            $(Base).hash($Integer(o), h)
        end
        )
        push!(ret.args, def)
    end
    push!(ret.args, def_has_batteries(T))
    return esc(ret)
end

end #module
